version: '3'

services:
  userinterface:
    build: userinterface
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - VITE_CHATBOT_SERVICE=http://chatbot:8000

  auth:
    build: authMicroservice
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://user:h{8KPhW+9U!kuAr@main_db:3306/chatbot_db
      - SECRET_KEY='rcGxdzPSCGSGnmlfkjydATFgVqehWBRNkQnmdJbUQTYxRxrlZG'
      - ALGORITHM="HS256"
      - ACCESS_TOKEN_EXPIRE_MINUTES="30"
      - ADMIN_GROUP_NAME="admin"
      - STAFF_GROUP_NAME="staff"
      - ALLOWED_ORIGINS="*"
      - ALLOWED_METHODS="*"
      - ALLOWED_HEADERS="*"
    depends_on:
      main_db:
        condition: service_healthy
    networks:
      - app_network

  chatbot:
    build: chatbotMicroservice
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=mysql://user:h{8KPhW+9U!kuAr@main_db:3306/chatbot_db
    depends_on:
      main_db:
        condition: service_healthy
    networks:
      - app_network

  main_db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rooth{8KPhW+9U!kuAr
      - MYSQL_DATABASE=chatbot_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=h{8KPhW+9U!kuAr
    # ports:
    #   - "3306:3306"
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network
    depends_on:
      - userinterface
      - chatbot
      - auth

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: