services:
  main_db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: chatbot_db
      MYSQL_USER: user
    secrets:
      - mysql_root_password
      - mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  auth:
    build: authMicroservice
    ports:
      - "8000:8000"
    depends_on:
      main_db:
        condition: service_healthy
        restart: true
    entrypoint: [ "sh", "-c", "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8000" ]
    read_only: true
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128M"
    env_file:
      - secret/dev/auth.env
    networks:
      - app-network

  chatbot:
    build: chatbotMicroservice
    ports:
      - "8001:8000"
    depends_on:
      main_db:
        condition: service_healthy
        restart: true
    entrypoint: [ "sh", "-c", "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8000" ]
    read_only: true
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128M"
    env_file:
      - secret/dev/chatbot.env
    networks:
      - app-network

  userinterface:
    build: userinterface
    command: npm run dev
    volumes:
      - ./userinterface:/src/app
      - /src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - secret/dev/userinterface.env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "254M"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/dev.prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128M"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - userinterface
      - chatbot
      - auth
      - prometheus

volumes:
  mysql_data:


networks:
  app-network:
    driver: bridge

secrets:
  mysql_root_password:
    file: secret/mysql_root_password.txt
  mysql_password:
    file: secret/mysql_user_password.txt
