services:
  userinterface:
    build: userinterface
    ports:
      - "3000:3000"
    networks:
      - thebookingbot_network
    # deploy:
    #   replicas: 2

  auth:
    build: authMicroservice
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/user_db
    depends_on:
      - db
    networks:
      - thebookingbot_network
    # deploy:
    #   replicas: 2

  chatbot:
    build: chatbotMicroservice
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/chatbot_db
    depends_on:
      - db
    networks:
      - thebookingbot_network
    # deploy:
    #   replicas: 2

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=chatbot_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - thebookingbot_network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - thebookingbot_network
    depends_on:
      - userinterface
      - chatbot
      - auth

networks:
  thebookingbot_network:
    driver: bridge

volumes:
  mysql_data: