# Generated by Django 5.1.1 on 2024-09-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbotMicroservice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotconfiguration",
            name="chatbot_id",
            field=models.CharField(
                default="95996ae5-408c-4ce2-8f0d-9e3bff6dd80c",
                max_length=36,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
