# Generated by Django 5.1.1 on 2024-09-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbotMicroservice", "0002_chatbotconfiguration_chatbot_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="options",
        ),
    ]
