# Generated by Django 5.1.1 on 2024-09-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbotMicroservice", "0003_remove_question_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="bot_id",
            new_name="bot",
        ),
    ]
