AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an EC2 instance with Docker Compose and Key Pair.

Parameters:
  EC2KeyPairName:
    Type: String
    Description: Key pair used to connect to the EC2 instance via SSH
    Default: the-booking-bot-ec2-keypair

  GithubPersonalAccessToken:
    Type: String
    Description: GitHub Personal Access Token (PAT) to clone the repository
    NoEcho: true # Hide the value in CloudFormation logs for security

Resources:
  # Security Group for the EC2 instance
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access to the EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Open to all (restrict for production)

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # Open to all (restrict for production)

  # EC2 Instance with Docker and Docker Compose installed
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t4g.micro
      KeyName: !Ref EC2KeyPairName
      ImageId: ami-0c8eea98010057bd0
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          # Update the system
          sudo apt update -y && \

          # Install necessary packages
          sudo apt install -y git && \

          # Install Docker
          sudo curl -fsSL https://get.docker.com -o get-docker.sh && \
          sudo sh get-docker.sh && \

          # Install Docker Compose
          DOCKER_COMPOSE_VERSION=1.29.2 && \
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
          sudo chmod +x /usr/local/bin/docker-compose && \

          # Verify installation
          docker --version && \
          docker compose version && \


          # Clone GitHub Repository
          GITHUB_REPO_URL=https://${GithubPersonalAccessToken}@github.com/Rahul-singh98/theBookingBot.git && \
          git clone -b microservices $GITHUB_REPO_URL /home/ec2-user/theBookingBot && \

          # Switch to the cloned directory and start the application
          cd /home/ec2-user/theBookingBot && \

          # Get public ip address
          PUBLIC_IP=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep -o '"public-ipv4":"[^"]*' | cut -d'"' -f4) && \

          # Set the file path
          FILE_PATH="docker-compose.yaml" && \

          sed -i "s/VITE_AUTH_API_URL=.*$/VITE_AUTH_API_URL=http:\/\/$PUBLIC_IP/" "$FILE_PATH" && \
          sed -i "s/VITE_CHATBOT_API_URL=.*$/VITE_CHATBOT_API_URL=http:\/\/$PUBLIC_IP/" "$FILE_PATH" && \

          # Build and run the image
          sudo docker compose up --build -d

Outputs:
  KeyPairName:
    Description: Name of the Key Pair created
    Value: !Ref EC2KeyPairName

  InstanceId:
    Description: ID of the EC2 instance
    Value: !Ref EC2Instance

  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp

  InstancePublicDNS:
    Description: Public DNS of the EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName
